"""16개 분류군 페르소나 데모 계정 시드.

각 페르소나(검진+문진 임상 프로필)로 운영 계정을 만들고, 서비스 계층을 직접
호출해 eGFR·app_group·예측 job(SHAP·AI가이드)을 실제 흐름대로 생성한다.

실행 순서(분류군 정합 보장):
  AuthService.signup → email_verified=True → 문진(create_survey) → 검진(create_health_check)
  검진이 최신 문진의 ckd_diagnosed/dialysis_type를 읽어 app_group을 배정한다.

사용 (EC2 fastapi 컨테이너 안에서 `uv run python` 으로 — 시스템 python엔 tortoise 없음):
  # 1) 컨테이너에 스크립트 복사 (scripts/는 볼륨 미마운트)
  docker compose cp scripts/seed_personas.py fastapi:/tmp/seed_personas.py
  # 2) DB 미접근 사전검증 — eGFR·예상 app_group 미리보기
  docker compose exec -T fastapi uv run python /tmp/seed_personas.py validate
  # 3) 실제 생성 (기존 16개 이메일만 삭제 후 재생성 — 멱등, demo@·실제유저 무관)
  docker compose exec -T fastapi uv run python /tmp/seed_personas.py apply
  # 4) 일부 계정만 재시드 (추가 인자로 이메일 지정 — 나머지 페르소나 무영향)
  docker compose exec -T fastapi uv run python /tmp/seed_personas.py apply c-male@healthypeople.kr c-female@healthypeople.kr

비밀번호는 16계정 공용 `Demo1234!`. 이메일은 분류군 기반(`{a~d,ckd,hd,pd,tx}-{male,female}@healthypeople.kr`).
"""

import asyncio
import sys
from datetime import date
from pathlib import Path

# 프로젝트 루트를 import path에 추가 (seed_demo_user.py와 동일 컨벤션).
# 컨테이너에서 /tmp로 복사해 실행하면 parent.parent가 "/"라 app을 못 찾으므로 /app도 명시 추가.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
if "/app" not in sys.path:
    sys.path.insert(0, "/app")

from tortoise import Tortoise

from app.core.db.databases import TORTOISE_ORM
from app.dtos.auth import SignUpRequest
from app.dtos.health_check import HealthCheckCreateRequest
from app.dtos.lifestyle_survey import LifestyleSurveyCreateRequest
from app.models.health_check import HealthCheck
from app.models.users import Gender, User
from app.services.auth import AuthService
from app.services.health_check import HealthCheckService
from app.services.lifestyle_survey import LifestyleSurveyService

PASSWORD = "Demo1234!"
CHECKED = date(2026, 6, 10)  # 검진일 = 설문일
THIS_YEAR = 2026

# 분류군 기반 ID. 각 dict: email/phone/name/gender/age/group + survey{ckd_diagnosed,dialysis_type 포함} + hc
PERSONAS = [
    {
        "email": "a-male@healthypeople.kr",
        "phone": "010-0000-0001",
        "name": "김민준",
        "gender": "MALE",
        "age": 64,
        "group": "A 신장집중관리",
        "hc": {
            "systolic_bp": 148,
            "diastolic_bp": 94,
            "fasting_glucose": 108,
            "creatinine": 2.3,
            "total_cholesterol": 198,
            "hdl_cholesterol": 42,
            "triglycerides": 168,
            "ldl_cholesterol": 122,
            "hemoglobin": 13.8,
            "ast": 32,
            "alt": 28,
            "urine_protein": "NEGATIVE",
            "urine_glucose": "POSITIVE",
            "weight": 72,
            "height": 168,
            "waist_circumference": 88,
        },
        "survey": {
            "smoking_status": "CURRENT",
            "drinking_frequency": "WEEKLY",
            "exercise_days_per_week": 1,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 1,
            "moderate_exercise_minutes": 20,
            "sitting_hours_per_day": 10,
            "sleep_hours_per_day": 5,
            "daily_water_intake": 1.0,
            "stress_level": "HIGH",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": True,
            "family_history_diabetes": True,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": True,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": False,
            "dialysis_type": "none",
        },
    },
    {
        "email": "a-female@healthypeople.kr",
        "phone": "010-0000-0002",
        "name": "이영숙",
        "gender": "FEMALE",
        "age": 71,
        "group": "A 신장집중관리",
        "hc": {
            "systolic_bp": 158,
            "diastolic_bp": 96,
            "fasting_glucose": 124,
            "creatinine": 1.9,
            "total_cholesterol": 215,
            "hdl_cholesterol": 38,
            "triglycerides": 192,
            "ldl_cholesterol": 138,
            "hemoglobin": 11.8,
            "ast": 29,
            "alt": 22,
            "urine_protein": "POSITIVE",
            "urine_glucose": "POSITIVE",
            "weight": 61,
            "height": 158,
            "waist_circumference": 88,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "OCCASIONALLY",
            "exercise_days_per_week": 1,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 1,
            "moderate_exercise_minutes": 15,
            "sitting_hours_per_day": 9,
            "sleep_hours_per_day": 5,
            "daily_water_intake": 1.0,
            "stress_level": "HIGH",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": True,
            "family_history_diabetes": True,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": True,
            "dm_diagnosed": True,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": False,
            "dialysis_type": "none",
        },
    },
    {
        "email": "b-male@healthypeople.kr",
        "phone": "010-0000-0003",
        "name": "박성호",
        "gender": "MALE",
        "age": 55,
        "group": "B 신장위험관리",
        "hc": {
            "systolic_bp": 138,
            "diastolic_bp": 85,
            "fasting_glucose": 106,
            "creatinine": 1.1,
            "total_cholesterol": 224,
            "hdl_cholesterol": 44,
            "triglycerides": 178,
            "ldl_cholesterol": 144,
            "hemoglobin": 15.2,
            "ast": 38,
            "alt": 42,
            "urine_protein": "POSITIVE",
            "urine_glucose": "NEGATIVE",
            "weight": 84,
            "height": 174,
            "waist_circumference": 94,
        },
        "survey": {
            "smoking_status": "PAST",
            "drinking_frequency": "WEEKLY",
            "exercise_days_per_week": 2,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 2,
            "moderate_exercise_minutes": 30,
            "sitting_hours_per_day": 9,
            "sleep_hours_per_day": 6,
            "daily_water_intake": 1.5,
            "stress_level": "MODERATE",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": True,
            "family_history_diabetes": False,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": False,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": False,
            "dialysis_type": "none",
        },
    },
    {
        "email": "b-female@healthypeople.kr",
        "phone": "010-0000-0004",
        "name": "최수진",
        "gender": "FEMALE",
        "age": 60,
        "group": "B 신장위험관리",
        "hc": {
            "systolic_bp": 126,
            "diastolic_bp": 82,
            "fasting_glucose": 142,
            "creatinine": 0.9,
            "total_cholesterol": 210,
            "hdl_cholesterol": 52,
            "triglycerides": 156,
            "ldl_cholesterol": 124,
            "hemoglobin": 12.4,
            "ast": 25,
            "alt": 20,
            "urine_protein": "POSITIVE",
            "urine_glucose": "NEGATIVE",
            "weight": 68,
            "height": 163,
            "waist_circumference": 87,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "OCCASIONALLY",
            "exercise_days_per_week": 2,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 2,
            "moderate_exercise_minutes": 25,
            "sitting_hours_per_day": 8,
            "sleep_hours_per_day": 6,
            "daily_water_intake": 1.5,
            "stress_level": "MODERATE",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": False,
            "family_history_diabetes": True,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": False,
            "dm_diagnosed": True,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": False,
            "dialysis_type": "none",
        },
    },
    {
        "email": "c-male@healthypeople.kr",
        "phone": "010-0000-0005",
        "name": "김철수",
        "gender": "MALE",
        "age": 68,
        "group": "C 신장사전관리",
        "hc": {
            "systolic_bp": 124,
            "diastolic_bp": 76,
            "fasting_glucose": 98,
            "creatinine": 1.1,
            "total_cholesterol": 215,
            "hdl_cholesterol": 38,
            "triglycerides": 220,
            "ldl_cholesterol": 133,
            "hemoglobin": 11.8,
            "ast": 28,
            "alt": 32,
            "urine_protein": "POSITIVE",
            "urine_glucose": "NEGATIVE",
            "weight": 80,
            "height": 170,
            "waist_circumference": 96,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "OCCASIONALLY",
            "exercise_days_per_week": 1,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 1,
            "moderate_exercise_minutes": 30,
            "sitting_hours_per_day": 9,
            "sleep_hours_per_day": 6,
            "daily_water_intake": 1.5,
            "stress_level": "MODERATE",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": False,
            "family_history_diabetes": False,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": False,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": True,
            "ckd_diagnosed": False,
            "dialysis_type": "none",
        },
    },
    {
        "email": "c-female@healthypeople.kr",
        "phone": "010-0000-0006",
        "name": "김순희",
        "gender": "FEMALE",
        "age": 76,
        "group": "C 신장사전관리",
        "hc": {
            "systolic_bp": 118,
            "diastolic_bp": 74,
            "fasting_glucose": 95,
            "creatinine": 0.68,
            "total_cholesterol": 202,
            "hdl_cholesterol": 38,
            "triglycerides": 153,
            "ldl_cholesterol": 129,
            "hemoglobin": 11.8,
            "ast": 22,
            "alt": 25,
            "urine_protein": "NEGATIVE",
            "urine_glucose": "NEGATIVE",
            "weight": 55,
            "height": 160,
            "waist_circumference": 78,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "OCCASIONALLY",
            "exercise_days_per_week": 2,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 2,
            "moderate_exercise_minutes": 30,
            "sitting_hours_per_day": 7,
            "sleep_hours_per_day": 6,
            "daily_water_intake": 1.5,
            "stress_level": "MODERATE",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": False,
            "family_history_diabetes": False,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": False,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": True,
            "ckd_diagnosed": False,
            "dialysis_type": "none",
        },
    },
    {
        "email": "d-male@healthypeople.kr",
        "phone": "010-0000-0007",
        "name": "윤재원",
        "gender": "MALE",
        "age": 42,
        "group": "D 건강습관형성",
        "hc": {
            "systolic_bp": 112,
            "diastolic_bp": 70,
            "fasting_glucose": 88,
            "creatinine": 0.88,
            "total_cholesterol": 178,
            "hdl_cholesterol": 62,
            "triglycerides": 88,
            "ldl_cholesterol": 98,
            "hemoglobin": 15.6,
            "ast": 24,
            "alt": 20,
            "urine_protein": "NEGATIVE",
            "urine_glucose": "NEGATIVE",
            "weight": 74,
            "height": 176,
            "waist_circumference": 82,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "OCCASIONALLY",
            "exercise_days_per_week": 4,
            "vigorous_exercise_days": 2,
            "vigorous_exercise_minutes": 30,
            "moderate_exercise_days": 2,
            "moderate_exercise_minutes": 40,
            "sitting_hours_per_day": 6,
            "sleep_hours_per_day": 7,
            "daily_water_intake": 2.0,
            "stress_level": "LOW",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": False,
            "family_history_diabetes": False,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": False,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": False,
            "dialysis_type": "none",
        },
    },
    {
        "email": "d-female@healthypeople.kr",
        "phone": "010-0000-0008",
        "name": "임하은",
        "gender": "FEMALE",
        "age": 38,
        "group": "D 건강습관형성",
        "hc": {
            "systolic_bp": 108,
            "diastolic_bp": 68,
            "fasting_glucose": 86,
            "creatinine": 0.72,
            "total_cholesterol": 172,
            "hdl_cholesterol": 68,
            "triglycerides": 76,
            "ldl_cholesterol": 90,
            "hemoglobin": 13.4,
            "ast": 20,
            "alt": 16,
            "urine_protein": "NEGATIVE",
            "urine_glucose": "NEGATIVE",
            "weight": 56,
            "height": 165,
            "waist_circumference": 68,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "NEVER",
            "exercise_days_per_week": 5,
            "vigorous_exercise_days": 1,
            "vigorous_exercise_minutes": 20,
            "moderate_exercise_days": 4,
            "moderate_exercise_minutes": 40,
            "sitting_hours_per_day": 5,
            "sleep_hours_per_day": 8,
            "daily_water_intake": 2.5,
            "stress_level": "VERY_LOW",
            "marital_status": "SINGLE",
            "is_pregnant": False,
            "family_history_hypertension": False,
            "family_history_diabetes": False,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": False,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": False,
            "dialysis_type": "none",
        },
    },
    {
        "email": "ckd-male@healthypeople.kr",
        "phone": "010-0000-0009",
        "name": "송태양",
        "gender": "MALE",
        "age": 67,
        "group": "비투석 CKD G4",
        "hc": {
            "systolic_bp": 152,
            "diastolic_bp": 92,
            "fasting_glucose": 118,
            "creatinine": 3.8,
            "total_cholesterol": 186,
            "hdl_cholesterol": 36,
            "triglycerides": 202,
            "ldl_cholesterol": 108,
            "hemoglobin": 10.2,
            "ast": 18,
            "alt": 14,
            "urine_protein": "POSITIVE",
            "urine_glucose": "NEGATIVE",
            "weight": 65,
            "height": 169,
            "waist_circumference": 86,
        },
        "survey": {
            "smoking_status": "PAST",
            "drinking_frequency": "OCCASIONALLY",
            "exercise_days_per_week": 1,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 1,
            "moderate_exercise_minutes": 15,
            "sitting_hours_per_day": 10,
            "sleep_hours_per_day": 5,
            "daily_water_intake": 1.0,
            "stress_level": "HIGH",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": True,
            "family_history_diabetes": False,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": True,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": True,
            "dialysis_type": "none",
        },
    },
    {
        "email": "ckd-female@healthypeople.kr",
        "phone": "010-0000-0010",
        "name": "윤미경",
        "gender": "FEMALE",
        "age": 64,
        "group": "비투석 CKD G4",
        "hc": {
            "systolic_bp": 148,
            "diastolic_bp": 90,
            "fasting_glucose": 112,
            "creatinine": 3.2,
            "total_cholesterol": 192,
            "hdl_cholesterol": 38,
            "triglycerides": 196,
            "ldl_cholesterol": 114,
            "hemoglobin": 9.8,
            "ast": 20,
            "alt": 16,
            "urine_protein": "POSITIVE",
            "urine_glucose": "NEGATIVE",
            "weight": 58,
            "height": 156,
            "waist_circumference": 84,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "NEVER",
            "exercise_days_per_week": 1,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 1,
            "moderate_exercise_minutes": 10,
            "sitting_hours_per_day": 10,
            "sleep_hours_per_day": 5,
            "daily_water_intake": 0.8,
            "stress_level": "HIGH",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": True,
            "family_history_diabetes": True,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": True,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": True,
            "dialysis_type": "none",
        },
    },
    {
        "email": "hd-male@healthypeople.kr",
        "phone": "010-0000-0011",
        "name": "한도준",
        "gender": "MALE",
        "age": 58,
        "group": "혈액투석",
        "hc": {
            "systolic_bp": 162,
            "diastolic_bp": 98,
            "fasting_glucose": 132,
            "creatinine": 9.2,
            "total_cholesterol": 168,
            "hdl_cholesterol": 32,
            "triglycerides": 224,
            "ldl_cholesterol": 98,
            "hemoglobin": 9.8,
            "ast": 16,
            "alt": 12,
            "urine_protein": "POSITIVE",
            "urine_glucose": "POSITIVE",
            "weight": 68,
            "height": 171,
            "waist_circumference": 85,
        },
        "survey": {
            "smoking_status": "CURRENT",
            "drinking_frequency": "NEVER",
            "exercise_days_per_week": 0,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 0,
            "moderate_exercise_minutes": 0,
            "sitting_hours_per_day": 12,
            "sleep_hours_per_day": 5,
            "daily_water_intake": 0.5,
            "stress_level": "VERY_HIGH",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": True,
            "family_history_diabetes": False,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": True,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": True,
            "dialysis_type": "hemodialysis",
        },
    },
    {
        "email": "hd-female@healthypeople.kr",
        "phone": "010-0000-0012",
        "name": "조은희",
        "gender": "FEMALE",
        "age": 55,
        "group": "혈액투석",
        "hc": {
            "systolic_bp": 158,
            "diastolic_bp": 96,
            "fasting_glucose": 128,
            "creatinine": 7.8,
            "total_cholesterol": 162,
            "hdl_cholesterol": 30,
            "triglycerides": 218,
            "ldl_cholesterol": 88,
            "hemoglobin": 9.4,
            "ast": 14,
            "alt": 10,
            "urine_protein": "POSITIVE",
            "urine_glucose": "POSITIVE",
            "weight": 52,
            "height": 160,
            "waist_circumference": 80,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "NEVER",
            "exercise_days_per_week": 0,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 0,
            "moderate_exercise_minutes": 0,
            "sitting_hours_per_day": 12,
            "sleep_hours_per_day": 5,
            "daily_water_intake": 0.5,
            "stress_level": "VERY_HIGH",
            "marital_status": "WIDOWED",
            "is_pregnant": False,
            "family_history_hypertension": False,
            "family_history_diabetes": True,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": True,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": True,
            "dialysis_type": "hemodialysis",
        },
    },
    {
        "email": "pd-male@healthypeople.kr",
        "phone": "010-0000-0013",
        "name": "배재현",
        "gender": "MALE",
        "age": 61,
        "group": "복막투석",
        "hc": {
            "systolic_bp": 154,
            "diastolic_bp": 92,
            "fasting_glucose": 152,
            "creatinine": 8.1,
            "total_cholesterol": 196,
            "hdl_cholesterol": 31,
            "triglycerides": 238,
            "ldl_cholesterol": 117,
            "hemoglobin": 10.6,
            "ast": 16,
            "alt": 13,
            "urine_protein": "POSITIVE",
            "urine_glucose": "POSITIVE",
            "weight": 66,
            "height": 170,
            "waist_circumference": 88,
        },
        "survey": {
            "smoking_status": "PAST",
            "drinking_frequency": "NEVER",
            "exercise_days_per_week": 1,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 1,
            "moderate_exercise_minutes": 15,
            "sitting_hours_per_day": 11,
            "sleep_hours_per_day": 5,
            "daily_water_intake": 0.8,
            "stress_level": "VERY_HIGH",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": True,
            "family_history_diabetes": False,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": True,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": True,
            "dialysis_type": "peritoneal",
        },
    },
    {
        "email": "pd-female@healthypeople.kr",
        "phone": "010-0000-0014",
        "name": "오미란",
        "gender": "FEMALE",
        "age": 62,
        "group": "복막투석",
        "hc": {
            "systolic_bp": 156,
            "diastolic_bp": 94,
            "fasting_glucose": 148,
            "creatinine": 7.4,
            "total_cholesterol": 192,
            "hdl_cholesterol": 34,
            "triglycerides": 248,
            "ldl_cholesterol": 108,
            "hemoglobin": 10.4,
            "ast": 14,
            "alt": 11,
            "urine_protein": "POSITIVE",
            "urine_glucose": "POSITIVE",
            "weight": 54,
            "height": 157,
            "waist_circumference": 82,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "NEVER",
            "exercise_days_per_week": 1,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 1,
            "moderate_exercise_minutes": 10,
            "sitting_hours_per_day": 11,
            "sleep_hours_per_day": 5,
            "daily_water_intake": 0.8,
            "stress_level": "VERY_HIGH",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": False,
            "family_history_diabetes": True,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": True,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": True,
            "dialysis_type": "peritoneal",
        },
    },
    {
        "email": "tx-male@healthypeople.kr",
        "phone": "010-0000-0015",
        "name": "서준혁",
        "gender": "MALE",
        "age": 52,
        "group": "신장이식",
        "hc": {
            "systolic_bp": 136,
            "diastolic_bp": 84,
            "fasting_glucose": 116,
            "creatinine": 1.6,
            "total_cholesterol": 204,
            "hdl_cholesterol": 46,
            "triglycerides": 172,
            "ldl_cholesterol": 128,
            "hemoglobin": 12.8,
            "ast": 28,
            "alt": 24,
            "urine_protein": "POSITIVE",
            "urine_glucose": "NEGATIVE",
            "weight": 71,
            "height": 173,
            "waist_circumference": 83,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "NEVER",
            "exercise_days_per_week": 3,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 3,
            "moderate_exercise_minutes": 30,
            "sitting_hours_per_day": 7,
            "sleep_hours_per_day": 7,
            "daily_water_intake": 2.0,
            "stress_level": "MODERATE",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": True,
            "family_history_diabetes": False,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": True,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": True,
            "dialysis_type": "transplant",
        },
    },
    {
        "email": "tx-female@healthypeople.kr",
        "phone": "010-0000-0016",
        "name": "문소연",
        "gender": "FEMALE",
        "age": 49,
        "group": "신장이식",
        "hc": {
            "systolic_bp": 132,
            "diastolic_bp": 82,
            "fasting_glucose": 112,
            "creatinine": 1.4,
            "total_cholesterol": 198,
            "hdl_cholesterol": 48,
            "triglycerides": 164,
            "ldl_cholesterol": 118,
            "hemoglobin": 12.2,
            "ast": 26,
            "alt": 22,
            "urine_protein": "POSITIVE",
            "urine_glucose": "NEGATIVE",
            "weight": 60,
            "height": 164,
            "waist_circumference": 79,
        },
        "survey": {
            "smoking_status": "NEVER",
            "drinking_frequency": "NEVER",
            "exercise_days_per_week": 3,
            "vigorous_exercise_days": 0,
            "vigorous_exercise_minutes": 0,
            "moderate_exercise_days": 3,
            "moderate_exercise_minutes": 30,
            "sitting_hours_per_day": 7,
            "sleep_hours_per_day": 7,
            "daily_water_intake": 2.0,
            "stress_level": "MODERATE",
            "marital_status": "MARRIED",
            "is_pregnant": False,
            "family_history_hypertension": False,
            "family_history_diabetes": True,
            "family_history_heart_disease": False,
            "family_history_dyslipidemia": False,
            "family_history_stroke": False,
            "htn_diagnosed": True,
            "dm_diagnosed": False,
            "dyslipidemia_diagnosed": False,
            "ckd_diagnosed": True,
            "dialysis_type": "transplant",
        },
    },
]


def _birthday(age: int) -> date:
    return date(THIS_YEAR - age, 5, 15)  # 5/15 < 오늘(6/16) → 만나이 = age


def validate(only_emails: list[str] | None = None) -> None:
    """DB 미접근. DTO 구성 + 순수 계산으로 eGFR·예상 app_group 미리보기.

    only_emails 지정 시 해당 이메일만 미리보기 (전체 16개 중 일부만 검증).
    """
    targets = [p for p in PERSONAS if only_emails is None or p["email"] in only_emails]
    print(f"{'EMAIL':30s} {'GROUP':16s} {'GENDER':7s} AGE  eGFR   예상_app_group")
    print("-" * 78)
    ok = 0
    for p in targets:
        # DTO 검증(타입·범위·enum·phone·birthday)
        SignUpRequest(
            email=p["email"],
            password=PASSWORD,
            name=p["name"],
            gender=Gender(p["gender"]),
            birth_date=_birthday(p["age"]),
            phone_number=p["phone"],
            consents=[],
        )
        ls = LifestyleSurveyCreateRequest(surveyed_date=CHECKED, **p["survey"])
        hc = HealthCheckCreateRequest(checked_date=CHECKED, **p["hc"])
        # 순수 계산
        egfr = HealthCheckService._estimate_egfr(hc.creatinine, p["age"], Gender(p["gender"]))
        dtype = ls.dialysis_type if ls.ckd_diagnosed else None
        grp = HealthCheckService._assign_app_group(
            egfr,
            hc.systolic_bp,
            hc.diastolic_bp,
            hc.fasting_glucose,
            ckd_diagnosed=ls.ckd_diagnosed,
            dialysis_type=dtype,
        )
        print(f"{p['email']:30s} {p['group']:16s} {p['gender']:7s} {p['age']:3d}  {egfr:6.1f}  {grp.value}")
        ok += 1
    print("-" * 78)
    print(f"검증 통과: {ok}/{len(targets)} (DTO·enum·범위·phone·birthday 전부 유효)")


async def apply(only_emails: list[str] | None = None) -> None:
    await Tortoise.init(config=TORTOISE_ORM)
    auth, hcs, lss = AuthService(), HealthCheckService(), LifestyleSurveyService()
    # only_emails 지정 시 해당 계정만 재시드(나머지 페르소나·demo@·실제 유저 무영향).
    targets = [p for p in PERSONAS if only_emails is None or p["email"] in only_emails]
    emails = [p["email"] for p in targets]

    # 멱등: 대상 이메일만 삭제(cascade). demo@·실제 유저는 건드리지 않음.
    existing = await User.filter(email__in=emails)
    for u in existing:
        print(f"  기존 계정 삭제: id={u.id} {u.email}")
        await u.delete()

    print(f"\n{'EMAIL':30s} {'GROUP':16s} eGFR   app_group")
    print("-" * 70)
    created = 0
    for p in targets:
        try:
            gender = Gender(p["gender"])
            user = await auth.signup(
                SignUpRequest(
                    email=p["email"],
                    password=PASSWORD,
                    name=p["name"],
                    gender=gender,
                    birth_date=_birthday(p["age"]),
                    phone_number=p["phone"],
                    consents=[],
                )
            )
            user.email_verified = True
            await user.save(update_fields=["email_verified", "updated_at"])

            # 문진 먼저 → 검진이 ckd_diagnosed/dialysis_type 읽어 app_group 배정
            await lss.create_survey(user.id, LifestyleSurveyCreateRequest(surveyed_date=CHECKED, **p["survey"]))
            await hcs.create_health_check(
                user.id, p["age"], gender, HealthCheckCreateRequest(checked_date=CHECKED, **p["hc"])
            )

            hc = await HealthCheck.filter(user_id=user.id).order_by("-id").first()
            egfr = f"{hc.egfr_estimated:.1f}" if hc and hc.egfr_estimated is not None else "-"
            grp = hc.app_group.value if hc and hc.app_group else "-"
            print(f"{p['email']:30s} {p['group']:16s} {egfr:>5s}  {grp}")
            created += 1
        except Exception as e:  # noqa: BLE001
            print(f"{p['email']:30s} 실패: {type(e).__name__}: {e}")
    print("-" * 70)
    print(f"생성 완료: {created}/{len(targets)}  (비밀번호 공용 = {PASSWORD})")
    await Tortoise.close_connections()


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "validate"
    only = sys.argv[2:] or None  # 추가 인자로 특정 이메일만 대상 (없으면 전체 16개)
    if mode == "apply":
        asyncio.run(apply(only))
    else:
        validate(only)
